version: '3.6'
services:
  db:
    image: 'postgres:12.4'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    ports:
      - '6543:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build:
      # Here we define that it should build from the current directory
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      RUNNING_IN_DOCKER: "true"
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - type: bind
        source: .
        target: /app
    command:
      - ./run.sh
  test:
    image: url_shortener_web
    command: mix test
    depends_on:
      - db
    environment:
      MIX_ENV: test
      PORT: 4001
    volumes:
      - .:/app 
volumes:
  pgdata: