version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: 'postgres:12.4'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build:
      # Here we define that it should build from the current directory
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
volumes:
  pgdata: